#!/bin/bash
#
# Removes everything in this working tree that a build, a test run or an
# `npm install` PUT there. Nothing it deletes is authored: every path below is
# either git-ignored or regenerated by a command named in the summary this
# script prints when it finishes.
#
# WHY THIS IS NOT clean.sh. `clean.sh` next to this file stops and removes every
# docker container, image, volume and network on the HOST — not this project's,
# the host's. That is a different and much broader thing than "clean the working
# tree", it needs sudo, and it is destructive to whatever else is running on the
# machine. The two were deliberately not merged: somebody who wants their disk
# space back from a checkout should not have to take down a colleague's
# database to get it. Docker stays clean.sh's job; the filesystem is this one's.
#
# WHAT IT REFUSES TO TOUCH, and each of these is a decision rather than an
# oversight:
#
#   *.tfstate, *.tfstate.*   Terraform state. It is supposed to live in S3
#                            (infra/bootstrap-state.sh) and a local copy is
#                            therefore already a mistake — but deleting one is
#                            how you lose track of real infrastructure that is
#                            still running and still costing money. A clean
#                            script must never be the thing that does that.
#   .terraform.lock.hcl      Pins provider versions. It is committed in some of
#                            the infra directories; removing it lets the next
#                            `init` resolve a different provider, which is a
#                            change to the infrastructure, not a cleanup.
#   *.swp                    Vim swap files are git-ignored, but a present one
#                            usually means an editor is OPEN on that file right
#                            now. Deleting it under a live session loses the
#                            recovery copy.
#   .claude/                 Ignored, but hand-authored: settings.local.json is
#                            configuration somebody wrote, not output.
#   sts/, api/node-ldapjs/   Git submodules. Only their node_modules go. The
#                            directories themselves cost a
#                            `git submodule update --init --recursive` to get
#                            back, and an EMPTY submodule directory fails later
#                            and elsewhere: npm installs a package with no
#                            main, and the error names a missing module rather
#                            than a missing checkout.
#   anything git tracks      Enforced at runtime, not just promised — see
#                            remove() below.
#
# Usage:
#   ./clean-artifacts.sh              # dependencies, build output, test output
#   ./clean-artifacts.sh -n           # list what would go, delete nothing
#   ./clean-artifacts.sh --terraform  # also the .terraform provider caches
#   ./clean-artifacts.sh --all        # everything above
#

set -euo pipefail

DRY_RUN=false
WITH_TERRAFORM=false

usage() {
  sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
  cat <<'USAGE'
Options:
  -n, --dry-run     Show what would be removed, with sizes. Delete nothing.
      --terraform   Also remove infra/**/.terraform provider caches (~700MB,
                    and getting them back needs `terraform init` and a network).
                    Never touches state or the provider lock file.
  -a, --all         --terraform, plus every default group.
  -h, --help        This text.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--dry-run)  DRY_RUN=true ;;
    --terraform)   WITH_TERRAFORM=true ;;
    -a|--all)      WITH_TERRAFORM=true ;;
    -h|--help)     usage; exit 0 ;;
    *)
      echo "clean-artifacts.sh: unknown option '$1'" >&2
      echo "Try './clean-artifacts.sh --help'." >&2
      exit 2
      ;;
  esac
  shift
done

# Run from the repository root whatever the caller's cwd is, and then REFUSE to
# run if that root is not this repository. The paths below are relative and
# several of them are `rm -rf` of a whole directory; a copy of this script
# dropped somewhere else, or a cwd nobody checked, is the way that turns into
# deleting an unrelated tree.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ "$REPO_ROOT" != "$PWD" ]]; then
  echo "clean-artifacts.sh: refusing to run — $PWD is not the root of a git repository." >&2
  exit 1
fi
# A sentinel from each half of the project, so this cannot run in some other
# checkout that merely happens to be a git root.
if [[ ! -f client/build.js || ! -f docker-compose.yml || ! -d tests ]]; then
  echo "clean-artifacts.sh: refusing to run — $PWD does not look like the oauth2-oidc-debugger checkout." >&2
  exit 1
fi

TOTAL_KB=0
REMOVED=0
SKIPPED=0

# size_kb PATH — disk usage in KB, 0 if absent. `du -s` counts the real blocks,
# so the totals printed here are what actually comes back on the filesystem.
size_kb() {
  du -sk "$1" 2>/dev/null | cut -f1 || echo 0
}

human() {
  local kb="$1"
  if   (( kb >= 1048576 )); then printf '%.1fG' "$(echo "$kb" | awk '{print $1/1048576}')"
  elif (( kb >= 1024    )); then printf '%.0fM' "$(echo "$kb" | awk '{print $1/1024}')"
  else printf '%dK' "$kb"
  fi
}

group() {
  printf '\n\033[1m%s\033[0m\n' "$1"
}

# remove PATH — the only thing in this script that deletes.
#
# The tracked-file guard is the important half. Every target below is
# git-ignored TODAY, but a .gitignore edit or a stray `git add -f` can put a
# real file inside one of these directories, and the failure mode is losing
# somebody's work to a command they thought was safe. So the question asked
# here is not "is this path in my list" but "does git know about anything
# underneath it" — and if it does, this skips it and says so, loudly, rather
# than deciding on the caller's behalf.
remove() {
  local target="$1"

  # Nothing absolute and nothing that climbs out of the tree, however it got
  # into the list.
  case "$target" in
    /*|*..*)
      echo "  !! refusing unsafe path: $target" >&2
      return
      ;;
  esac

  [[ -e "$target" ]] || return 0

  local tracked
  tracked="$(git ls-files -- "$target" | head -1)"
  if [[ -n "$tracked" ]]; then
    printf '  \033[33mSKIP\033[0m %-44s git tracks %s\n' "$target" "$tracked"
    SKIPPED=$((SKIPPED + 1))
    return
  fi

  local kb
  kb="$(size_kb "$target")"
  TOTAL_KB=$((TOTAL_KB + kb))
  REMOVED=$((REMOVED + 1))

  if [[ "$DRY_RUN" == true ]]; then
    printf '  would remove %-40s %8s\n' "$target" "$(human "$kb")"
  else
    printf '  removed      %-40s %8s\n' "$target" "$(human "$kb")"
    rm -rf -- "$target"
  fi
}

if [[ "$DRY_RUN" == true ]]; then
  echo "DRY RUN — nothing will be deleted."
fi

# ---------------------------------------------------------------------------
# Installed dependencies.
#
# Four package roots, plus the node-ldapjs submodules. The submodule
# DIRECTORIES are never touched — only a node_modules inside one, which npm
# creates when its own dependencies are installed there rather than hoisted.
# ---------------------------------------------------------------------------
group "Installed dependencies (restore: npm ci)"
remove node_modules
remove api/node_modules
remove client/node_modules
remove tests/node_modules
remove extension/node_modules
remove sts/node_modules
remove api/node-ldapjs/node_modules
remove sts/node-ldapjs/node_modules

# ---------------------------------------------------------------------------
# Build output.
#
# client/public/js is the 38 browserify bundles: client/Dockerfile builds them
# INSIDE the image, one `browserify src/X.js -o public/js/X.js` per entry, so a
# fresh checkout does not have them and a local `node server.js` does. dist/ is
# build.js's static-site copy of the same thing.
#
# The two data.js are copies of common/data.js that the Dockerfiles stage and a
# local run has to stage by hand, and api/xmldsig.js is the same arrangement
# for common/xmldsig.js — the api signs the SAML bindings with the module the
# browser signs them with, so it is staged rather than duplicated;
# version.js/version.json are per-build stamps written by
# client/version.js --stamp. All of them are transient by construction — a
# committed one would make a build report a version it is not.
# ---------------------------------------------------------------------------
group "Build output (restore: see the notes printed at the end)"
remove client/dist
remove client/public/js
remove client/public/version.json
remove client/src/data.js
remove extension/dist
remove api/data.js
remove api/xmldsig.js
remove api/version.js
remove api/version.json

# ---------------------------------------------------------------------------
# Test and coverage output.
#
# tests/report and coverage/ are the two biggest things in the tree by a wide
# margin. The SAML SP key pair and the downloaded IdP metadata are per-run
# artifacts of common/common.sh (generateSpKeyPair, download_saml_metadata) and
# a stale copy is worse than an absent one: the next run regenerates the key,
# and metadata from a previous run points at an IdP that may no longer exist.
# ---------------------------------------------------------------------------
group "Test and coverage output (restore: re-run the tests)"
remove coverage
remove tests/report
remove tests/fixtures
remove tests/saml-idp-metadata.xml
remove saml-idp-metadata.xml
remove tests/sp-key.pem
remove tests/sp-cert.pem
remove sp-key.pem
remove sp-cert.pem

# ---------------------------------------------------------------------------
# Per-run rendered configuration. walt.id's config carries THAT RUN's issuer
# key, so it is regenerated rather than reused.
# ---------------------------------------------------------------------------
group "Per-run rendered config (restore: the next test run renders it)"
remove waltid/generated-config
remove waltid/generated-verifier-config

# ---------------------------------------------------------------------------
# Terraform provider caches. Opt-in because getting them back is a ~700MB
# download and needs a network, which is not what most callers of a clean
# script are asking for. State and the provider lock file are excluded above
# and are not listed here at all.
# ---------------------------------------------------------------------------
if [[ "$WITH_TERRAFORM" == true ]]; then
  group "Terraform provider caches (restore: terraform init)"
  while IFS= read -r dir; do
    remove "${dir#./}"
  done < <(find infra -type d -name '.terraform' 2>/dev/null | sort)
  while IFS= read -r plan; do
    remove "${plan#./}"
  done < <(find infra -type f \( -name '*.tfplan' -o -name 'crash.log' -o -name 'crash.*.log' \) 2>/dev/null | sort)
else
  group "Terraform provider caches"
  echo "  skipped — pass --terraform to include them ($(human "$( { find infra -type d -name '.terraform' -exec du -sk {} + 2>/dev/null || echo 0; } | awk '{s+=$1} END {print s+0}')") on disk)"
fi

# ---------------------------------------------------------------------------

printf '\n\033[1m%s\033[0m\n' "Summary"
if [[ "$DRY_RUN" == true ]]; then
  printf '  %d path(s) would be removed, reclaiming %s.\n' "$REMOVED" "$(human "$TOTAL_KB")"
else
  printf '  %d path(s) removed, %s reclaimed.\n' "$REMOVED" "$(human "$TOTAL_KB")"
fi
if (( SKIPPED > 0 )); then
  printf '  %d path(s) SKIPPED because git tracks something inside them (listed above).\n' "$SKIPPED"
fi

cat <<'NOTES'

To get a working tree back:

  npm ci                                     # in api/, client/, tests/, and sts/
  cp common/data.js api/data.js              # both services require ./data.js
  cp common/data.js client/src/data.js
  cp common/xmldsig.js api/xmldsig.js        # the api's SAML signing
  (cd client && npm run build)               # dist/ and the bundles

  # Or, for a local run without docker, build the bundles in place — one per
  # browserify entry in client/Dockerfile, into the public/js this removed:
  cd client
  grep -oP 'browserify src/\K[a-z0-9_]+(?=\.js)' Dockerfile | sort -u | while read -r b; do
    CONFIG_FILE=./src/env/local.js ./node_modules/.bin/browserify \
      src/$b.js -o public/js/$b.js --standalone $b \
      -t [ envify purge --CONFIG_FILE ./env/local.js ]
  done

Docker containers, images and volumes are clean.sh's job, not this script's.
NOTES
