#!/bin/bash
#
# Generate the TLS certificate the api and the client serve.
#
# ---------------------------------------------------------------------------
# WHO NEEDS THIS AND WHO DOES NOT.
#
# The four test launchers (./local-run-tests.sh, ./docker-run-tests.sh,
# ./run-coverage.sh, ./remote-run-tests.sh) call
# generateStackTlsCertificate() themselves and need nothing from here. This
# script is for the one documented path that has no launcher in front of it —
# the repo-root CLAUDE.md's
#
#     CONFIG_FILE=./env/local.js docker-compose up
#
# — where compose mounts ./generated-tls and nothing has written it.
#
# Both services set `https: true` in their local configuration, so without a
# certificate they refuse to bind and say so, naming this script. That is
# deliberate: a service that quietly invented a key pair would be up, serving
# something nothing else in the stack trusts.
#
# WHAT THIS WRITES, AND WHICH FILE YOU ACTUALLY TRUST.
#
# Three certificates, from client/src/x509.js's own `root-ca`, `issuing-ca`
# and `tls-server` profiles — the same three the PKI page offers:
#
#   ./generated-tls-ca/stack-tls-root.pem   the Root CA. TRUST THIS ONE.
#   ./generated-tls-ca/stack-tls-issuing.pem  the Issuing CA under it
#   ./generated-tls/stack-tls-cert.pem      leaf + issuing + root, as served
#
# THE CA DIRECTORY IS REUSED AND THE LEAF IS NOT. Re-running this issues a
# fresh leaf from the SAME root, so a root you have already imported into a
# browser or an OS trust store keeps working and there is nothing to accept
# again. That is the whole point of the hierarchy: a trust decision names a
# key, and before this the only key was the leaf, which changed every time.
# --rotate-ca throws the CA away and starts over, which invalidates that trust
# on purpose.
#
# It is also why the CA lives OUTSIDE ./generated-tls: compose bind-mounts
# that directory into the api and the client, and the root's private key —
# the one a browser has been told to trust — has no business in a container
# that never signs anything.
#
# Until you trust the root, browsers show an interstitial, and they show it
# PER ORIGIN: the UI on :3000 and the api on :4000 are two, and nothing ever
# navigates to the second, which is why its absence arrives as a CORS error.
# The SubjectAltNames cover localhost, client, api and the two loopback
# literals.
# ---------------------------------------------------------------------------
set -e

CURRENT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "${CURRENT_DIR}"

check_return_code()
{
  if [ "${1}" -ne 0 ];
  then
    echo "Failed with exit code ${1}." >&2
    exit "${1}"
  fi
}

. "${CURRENT_DIR}/common/common.sh"

# The compose files' default bind-mount source, so `docker-compose up` finds
# it with nothing exported. STACK_TLS_DIR overrides it, and the launchers set
# their own throwaway directory instead.
STACK_TLS_DIR="${STACK_TLS_DIR:-${CURRENT_DIR}/generated-tls}"
export STACK_TLS_DIR

# WHERE THE CERTIFICATE AUTHORITY IS KEPT, AND WHY IT SURVIVES THIS.
# Outside ./generated-tls, because compose bind-mounts that into both
# containers and the root private key does not belong in one. Unset, the
# generator would put the CA under the output directory and it would be
# thrown away with the leaf — which is right for the test launchers and wrong
# here, since reusing the root is what saves you from trusting it again.
STACK_TLS_CA_DIR="${STACK_TLS_CA_DIR:-${CURRENT_DIR}/generated-tls-ca}"
export STACK_TLS_CA_DIR

# Regenerating is the point of re-running this, so the LEAF goes rather than
# being reused — generateStackTlsCertificate() treats an existing pair as one
# the caller supplied. The CA directory is deliberately not touched: see
# above, and use --rotate-ca to replace it.
rm -f "${STACK_TLS_DIR}/stack-tls-cert.pem" "${STACK_TLS_DIR}/stack-tls-key.pem"
unset STACK_TLS_CERT_FILE STACK_TLS_KEY_FILE

# --rotate-ca is handled here rather than passed through, because the CA is
# generated by the node script and the only way to ask for a new one is to
# have nothing on disk when it looks.
if [ "${1:-}" = "--rotate-ca" ];
then
  echo "Rotating the CA: everything that trusted the old root stops" \
       "trusting this stack."
  rm -rf "${STACK_TLS_CA_DIR}"
  shift
fi

generateStackTlsCertificate "${CURRENT_DIR}" "${1:-}"
check_return_code $?

echo
echo "Wrote:"
echo "  ${STACK_TLS_CERT_FILE}  (leaf + issuing CA + root, as served)"
echo "  ${STACK_TLS_KEY_FILE}"
echo "  ${STACK_TLS_CA_DIR}/stack-tls-root.pem  <-- TRUST THIS ONE"
echo
echo "Root CA SHA-256 fingerprint:"
openssl x509 -in "${STACK_TLS_CA_DIR}/stack-tls-root.pem" \
  -noout -fingerprint -sha256
echo
echo "Leaf SHA-256 fingerprint:"
openssl x509 -in "${STACK_TLS_CERT_FILE}" -noout -fingerprint -sha256
echo
echo "Trust the ROOT once and every later run of this script is trusted"
echo "too — the leaf is reissued from the same root, so nothing has to be"
echo "accepted again. Until then a browser shows an interstitial PER"
echo "ORIGIN, and the api on :4000 is a second one that nothing navigates"
echo "to, which is why its absence shows up as a CORS error."
echo
echo "Now: CONFIG_FILE=./env/local.js docker-compose up"
echo "Then open https://localhost:3000 and, if you have not trusted"
echo "the root, accept the interstitial on :3000 AND on :4000."
